require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "**/Gemfile"
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120
Rails/FilePath:
  EnforcedStyle: arguments
# Spec blocks always get lengthy
Metrics/BlockLength:
  Exclude:
    - spec/**/*
# Save some DB hits with multiple expectations
RSpec/MultipleExpectations:
  Max: 3
